'use client';
import {useEffect,useState} from 'react';
import type {Niche,SocialPlatform} from '@/lib/trends';
import type {FeedPost,FeedSession} from '@/lib/feed-collector';
type Board={sessions:Omit<FeedSession,'pairHash'|'tokenHash'>[];posts:FeedPost[]};
const date=(v:string)=>new Date(v).toLocaleString('en-AU',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
const number=(v:number)=>Intl.NumberFormat('en',{notation:'compact'}).format(v);
export default function FeedDiscoveries({niches,onWatched}:{niches:Niche[];onWatched:()=>Promise<void>}){
 const [data,setData]=useState<Board>({sessions:[],posts:[]}),[platform,setPlatform]=useState<SocialPlatform>('instagram'),[nicheId,setNicheId]=useState(niches[0]?.id??''),[minutes,setMinutes]=useState(2),[maxPosts,setMaxPosts]=useState(10),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[filter,setFilter]=useState('all');
 useEffect(()=>{let live=true;const load=()=>fetch('/api/feed-collector').then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(live)setData(d);}).catch(e=>{if(live)setError(e.message);});load();const timer=setInterval(load,5000);return()=>{live=false;clearInterval(timer);};},[]);
 async function action(action:string,id?:string){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/feed-collector',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id,platform,nicheId,minutes,maxPosts})});const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);if(action==='watch'){await onWatched();setNotice('Creator added to the watchlist. Scan now to discover their public posts.');}if(action==='verify')setNotice('Checked up to 10 posts. Unavailable public counters are marked below.');}catch(e){setError(e instanceof Error?e.message:'Request failed');}finally{setBusy(false);}}
 const active=data.sessions.find(s=>s.status==='waiting'||s.status==='running');
 const posts=data.posts.filter(p=>filter==='all'||p.nicheId===filter).sort((a,b)=>(b.verified?.views??-1)-(a.verified?.views??-1)||b.lastSeen.localeCompare(a.lastSeen));
 const control='block mt-1 bg-bb-surface2 border border-bb-border rounded-lg p-2.5 text-sm';
 return <div className="space-y-5">
  <section className="card p-5 space-y-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="eyebrow text-bb-teal">Personalised feed research</p><h2 className="text-xl font-semibold mt-2">Feed discoveries</h2><p className="text-sm text-bb-muted mt-2 max-w-3xl">Collect posts from your Instagram Explore grid or TikTok For You feed. Instagram Reels also works. Start a short session in Chrome; HQ saves visible post links, captions and counters as you scroll.</p></div><a href="/api/feed-collector/extension" className="text-sm text-bb-blue border border-bb-blue/30 rounded-lg px-3 py-2 h-fit">Download Chrome extension</a></div>
  <details className="text-sm text-bb-muted"><summary className="cursor-pointer text-bb-fg">First-time setup & how to use</summary><ol className="list-decimal pl-5 mt-3 space-y-2"><li>Download and unzip the extension. In Chrome, open <code>chrome://extensions</code>, enable Developer mode, choose Load unpacked and select the unzipped folder. Keep that folder in place.</li><li>Choose a research niche and limits below, then create a session. It will appear automatically in the extension.</li><li>Open your signed-in Instagram Explore page (instagram.com/explore/) or TikTok For You feed in Chrome. Click the HQ Feed Collector extension, choose your waiting session and press Start collection. No pairing code needed.</li><li>Keep the feed tab visible while it advances. Stop from its overlay, the extension or HQ. Results appear here automatically.</li></ol><p className="mt-3">The extension runs only when you start it. It pauses when the tab is hidden and stops at the time/post limit, on navigation or if the feed stops advancing. It never likes, follows or comments. HQ must be running locally on port 3150. Site layout changes, login walls and verification prompts can interrupt collection.</p></details>
  <div className="flex flex-wrap items-end gap-4"><label className="text-xs text-bb-muted">Feed platform<select aria-label="Feed platform" value={platform} onChange={e=>setPlatform(e.target.value as SocialPlatform)} className={control}><option value="instagram">Instagram</option><option value="tiktok">TikTok</option></select></label><label className="text-xs text-bb-muted">Research niche<select aria-label="Feed research niche" value={nicheId} onChange={e=>setNicheId(e.target.value)} className={control}>{niches.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><label className="text-xs text-bb-muted">Time limit<select aria-label="Feed time limit" value={minutes} onChange={e=>setMinutes(Number(e.target.value))} className={control}>{[2,5,10].map(n=><option key={n} value={n}>{n} minutes</option>)}</select></label><label className="text-xs text-bb-muted">Post limit<select aria-label="Feed post limit" value={maxPosts} onChange={e=>setMaxPosts(Number(e.target.value))} className={control}>{[10,25,50,100].map(n=><option key={n}>{n}</option>)}</select></label><button disabled={busy||!!active||!nicheId} onClick={()=>action('create')} className="rounded-lg bg-bb-teal/15 border border-bb-teal/40 text-bb-teal px-4 py-2.5 text-sm disabled:opacity-40">Create feed session</button><a href={platform==='instagram'?'https://www.instagram.com/explore/':'https://www.tiktok.com/foryou'} target="_blank" rel="noreferrer" className="text-sm text-bb-blue py-2.5">{platform==='instagram'?'Open Instagram Explore ↗':'Open TikTok For You ↗'}</a></div>
  {active&&<div className="rounded-xl border border-bb-teal/30 bg-bb-teal/5 p-4 space-y-3"><div className="flex flex-wrap justify-between gap-3"><p className="text-sm"><strong className="capitalize">{active.status}</strong> · {active.platform} · {active.collected.length}/{active.maxPosts} posts · {active.minutes} min maximum{active.lastSeen&&<span className="text-bb-muted"> · Last contact {date(active.lastSeen)}</span>}</p><button disabled={busy} onClick={()=>action('stop',active.id)} className="text-sm text-bb-warn">Stop session</button></div>{active.status==='waiting'&&<p className="text-sm text-bb-muted">Ready to connect. Open your feed in Chrome, click HQ Feed Collector and press Start. The extension finds this session automatically. Start within 10 minutes.</p>}</div>}
  <p className="text-xs text-bb-dim">Explore tiles may show only a post link; Check public views fills in available creator names and captions. Research niche is your chosen collection folder, not an automatic relevance verdict. A personalised recommendation is not proof of a platform-wide trend. Feed counters remain labelled as visible; public view checks run separately. No passwords, cookies or messages are collected.</p>
  </section>
  {error&&<p role="alert" className="text-sm text-bb-danger">{error}</p>}{notice&&<p role="status" className="text-sm text-bb-teal">{notice}</p>}
  <div className="flex flex-wrap justify-between items-center gap-3"><p className="text-sm text-bb-muted">{posts.length} saved posts · ranked by verified public views when available</p><div className="flex gap-3"><select aria-label="Filter feed niche" value={filter} onChange={e=>setFilter(e.target.value)} className={control}><option value="all">All research niches</option>{niches.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select><button disabled={busy||!data.posts.length} onClick={()=>action('verify')} className="text-sm text-bb-blue disabled:opacity-40">{busy?'Working…':'Check public views'}</button></div></div>
  {posts.length?<div className="grid lg:grid-cols-2 gap-4">{posts.map(p=>{const watched=niches.find(n=>n.id===p.nicheId)?.[p.platform]?.includes(p.handle);return <article key={p.id} className="card p-5 space-y-3"><div className="flex justify-between gap-3 text-xs text-bb-muted"><span>{p.platform} · {niches.find(n=>n.id===p.nicheId)?.name??'Removed niche'}</span><span>{date(p.firstSeen)}</span></div><a href={p.url} target="_blank" rel="noreferrer" className="block text-bb-blue text-sm">{p.handle?`@${p.handle}`:'Open post'} ↗</a><p className="text-sm whitespace-pre-line line-clamp-4">{p.caption||'No readable caption in the feed.'}</p><div className="flex flex-wrap gap-4 text-sm">{p.verified&&<strong className="text-bb-teal">{number(p.verified.views)} public views</strong>}{Object.entries(p.visible).map(([k,v])=><span key={k}>{v} {k} <span className="text-bb-dim text-xs">visible in feed</span></span>)}</div><p className="text-xs text-bb-dim">{p.checkError||(!p.verified?'Awaiting a public view check.':`Public views checked ${date(p.verified.at)}`)}</p><button disabled={busy||!p.handle||watched} onClick={()=>action('watch',p.id)} className="text-xs text-bb-blue disabled:opacity-40">{watched?'Account watched':'Watch this creator'}</button></article>;})}</div>:<div className="card p-8 text-center text-bb-muted">Start a feed session to collect your first discoveries.</div>}
  {data.sessions.length>0&&<details className="card p-4 text-xs text-bb-muted"><summary className="cursor-pointer">Session history ({data.sessions.length})</summary><div className="space-y-3 mt-3">{data.sessions.map(s=><p key={s.id}>{date(s.createdAt)} · {s.platform} · {s.status} · {s.collected.length} posts{s.reason?` · ${s.reason}`:''}</p>)}</div></details>}
 </div>;
}
