'use client';
import {useState} from 'react';
import {rankCompetitorPosts,type PostMetric} from '@/lib/trend-ranking';
import {videoPlatform,videoUrl,type Video,type Creator} from '@/lib/trends';
const number=(n:number)=>Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(n);
const ratioNumber=(n:number)=>Intl.NumberFormat('en',{maximumSignificantDigits:3}).format(n);
export default function TopCompetitorPosts({videos,creators,now}:{videos:Video[];creators:Creator[];now:number}){
 const [metric,setMetric]=useState<PostMetric>('views'),[days,setDays]=useState(30),[account,setAccount]=useState(''),[one,setOne]=useState(false);
 const accounts=[...new Set(videos.filter(v=>videoPlatform(v)!=='youtube').map(v=>`${videoPlatform(v)}:${v.channel.toLowerCase()}`))].sort();
 const ranked=rankCompetitorPosts(videos,creators,{metric,days,account,onePerAccount:one},now);
 return <section aria-label="Top competitor posts" className="space-y-4"><div className="card p-5 space-y-3"><h2 className="text-lg font-semibold">Best-performing competitor posts</h2><p className="text-sm text-bb-muted">Ranked from the public Instagram and TikTok posts collected from watched accounts. This is the observed sample, not their complete post history.</p>
 <div className="flex flex-wrap gap-4"><label className="text-xs">Rank by<select aria-label="Rank competitor posts by" value={metric} onChange={e=>setMetric(e.target.value as PostMetric)} className="block bg-bb-surface2 border border-bb-border rounded-lg p-2"><option value="views">Most views</option><option value="ratio">Views per follower</option><option value="velocity">Fastest current growth</option></select></label><label className="text-xs">Published<select aria-label="Competitor post period" value={days} onChange={e=>setDays(Number(e.target.value))} className="block bg-bb-surface2 border border-bb-border rounded-lg p-2"><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option></select></label><label className="text-xs">Account<select aria-label="Competitor account" value={account} onChange={e=>setAccount(e.target.value)} className="block bg-bb-surface2 border border-bb-border rounded-lg p-2"><option value="">All collected accounts</option>{accounts.map(a=><option key={a} value={a}>{a.replace(':',' · @')}</option>)}</select></label><label className="text-xs flex items-center gap-2"><input type="checkbox" checked={one} onChange={e=>setOne(e.target.checked)}/>Best post per account</label></div>
 <p className="text-xs text-bb-dim">{ranked.length} ranked posts. Views measure reach, not engagement or conversions. Views per follower uses the current audience, not followers at publication, and excludes unavailable or stale counts. Growth needs repeat measurements. Use the platform filter above for like-for-like comparisons.</p></div>
 {ranked.length?ranked.slice(0,100).map((r,i)=><article key={r.video.id} className="card p-5 space-y-3"><div className="flex justify-between gap-4"><p className="text-sm text-bb-blue">#{i+1} · {videoPlatform(r.video)} · @{r.video.channel}</p><strong className="text-bb-teal">{metric==='views'?`${number(r.views)} views`:metric==='ratio'?`${ratioNumber(r.ratio!)}× views / follower`:`${number(r.velocity!)} new views / hr`}</strong></div><a href={videoUrl(r.video)} target="_blank" rel="noreferrer" className="block text-sm hover:underline">{r.video.title} ↗</a><div className="flex flex-wrap gap-4 text-xs text-bb-muted"><span>{number(r.views)} views</span><span>{r.followers==null?'Audience unavailable':`${number(r.followers)} followers`}</span><span>{r.ratio==null?'Ratio unavailable':`${ratioNumber(r.ratio)}× views / follower`}</span></div><p className="text-xs text-bb-dim">Published {new Date(r.video.publishedAt!).toLocaleDateString('en-AU')} · Measured {new Date(r.checkedAt).toLocaleString('en-AU')}{r.stale?' · Older measurement; awaiting refresh':''}</p></article>):<p className="card p-6 text-sm text-bb-muted">No measured posts match these filters yet. Scan watched accounts, broaden the period, or choose Most views if growth or audience counts are unavailable.</p>}
 </section>;
}
