'use client';
import Link from 'next/link';
import TrendWatchlist from './TrendWatchlist';
import TrendDiscovery from './TrendDiscovery';
import TopCompetitorPosts from './TopCompetitorPosts';
import FeedDiscoveries from './FeedDiscoveries';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,RefreshCw,Radio,SlidersHorizontal,Search,Activity} from 'lucide-react';
import {MAX_NICHES,DEFAULT_NICHES,BREAKOUT_RULES,smallAccountBreakouts,PLATFORMS,videoPlatform,videoUrl,STAGES,type Niche,type Stage,type Trend,type Video} from '@/lib/trends';
import type {radar} from '@/lib/trend-store';
type Board=ReturnType<typeof radar>;
const number=(n:number)=>Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(n);
const date=(s:string)=>new Date(s).toLocaleString('en-AU',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
const tone:Record<Stage,string>={Emerging:'text-bb-teal border-bb-teal/30 bg-bb-teal/10','Breaking out':'text-bb-violet border-bb-violet/30 bg-bb-violet/10',Established:'text-bb-blue border-bb-blue/30 bg-bb-blue/10',Fading:'text-bb-warn border-bb-warn/30 bg-bb-warn/10',Watching:'text-bb-muted border-bb-border bg-bb-surface2',Stale:'text-bb-danger border-bb-danger/30 bg-bb-danger/10'};
function Spark({video}:{video:Video}){
 const rows=video.readings.slice(-24);if(rows.length<2)return <span className="text-xs text-bb-dim">First measurement</span>;
 const min=Math.min(...rows.map(r=>r.views)),max=Math.max(...rows.map(r=>r.views));
 const start=Date.parse(rows[0].at),end=Date.parse(rows.at(-1)!.at);
 const points=rows.map(r=>`${4+(Date.parse(r.at)-start)/(end-start||1)*132},${32-(r.views-min)/(max-min||1)*26}`).join(' ');
 return <svg viewBox="0 0 140 38" className="h-10 w-36 text-bb-teal" role="img" aria-label={`View count: ${rows.map(r=>number(r.views)).join(', ')}`}><polyline points={points} fill="none" stroke="currentColor" strokeWidth="2"/></svg>;
}
function Evidence({video}:{video:Video}){
 return <a href={videoUrl(video)} target="_blank" rel="noreferrer" className="flex gap-3 rounded-xl border border-bb-border/60 p-3 hover:border-bb-blue/50 min-w-0">
  {videoPlatform(video)==='youtube'?<img src={`https://i.ytimg.com/vi/${video.id}/mqdefault.jpg`} alt="" loading="lazy" className="w-28 h-16 object-cover rounded-lg shrink-0"/>:<div className="w-20 h-16 rounded-lg shrink-0 grid place-items-center bg-bb-violet/10 border border-bb-violet/20 text-xs text-bb-violet">{videoPlatform(video)==='instagram'?'Instagram':'TikTok'}</div>}
  <div className="min-w-0 flex-1"><p className="text-sm line-clamp-2">{video.title}</p><p className="mt-1 text-xs text-bb-muted">{video.channel} · {number(video.readings.at(-1)!.views)} views <ArrowUpRight className="inline w-3 h-3"/></p><p className="mt-1 text-[10px] text-bb-dim">Published {video.publishedAt?date(video.publishedAt):'unknown'} · checked {date(video.readings.at(-1)!.at)}</p></div>
 </a>;
}
export default function TrendRadar({business,initial}:{business:string;initial:Board}){
 const [data,setData]=useState(initial),[niche,setNiche]=useState('all'),[network,setNetwork]=useState('all'),[stage,setStage]=useState('all'),[search,setSearch]=useState('');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[settings,setSettings]=useState(false),[draft,setDraft]=useState<Niche[]>(initial.niches),[selected,setSelected]=useState<Trend|null>(null);
 const dialog=useRef<HTMLElement>(null);
 useEffect(()=>{if(!selected)return;const previous=document.activeElement as HTMLElement|null;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setSelected(null);if(e.key==='Tab'){const els=Array.from(dialog.current?.querySelectorAll<HTMLElement>('button,a[href]')??[]);if(!els.length)return;const first=els[0],last=els.at(-1)!;if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',onKey);return()=>{document.removeEventListener('keydown',onKey);previous?.focus();};},[selected]);
 const [view,setView]=useState<'trends'|'posts'|'top'|'breakouts'|'accounts'|'discovery'|'feed'|'history'>('trends');
 const [breakoutRules,setBreakoutRules]=useState(BREAKOUT_RULES);
 useEffect(()=>{const timer=setInterval(()=>{fetch('/api/trends').then(r=>r.ok?r.json():null).then(d=>{if(d)setData(d);}).catch(()=>{});},30000);return()=>clearInterval(timer);},[]);
 async function action(action:string,niches?:Niche[]){
  setBusy(true);setError('');
  try{const r=await fetch('/api/trends',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,niches})});const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);if(action==='configure')setSettings(false);return true;}
  catch(e){setError(e instanceof Error?e.message:'Request failed');return false;}finally{setBusy(false);}
 }
 const rows=data.trends.filter(t=>(network==='all'||t.platform===network)&&(niche==='all'||t.nicheId===niche)&&(stage==='all'||t.stage===stage)&&(!search||`${t.title} ${t.videos.map(v=>v.title).join(' ')}`.toLowerCase().includes(search.toLowerCase())));
 const posts=data.videos.filter(v=>(network==='all'||videoPlatform(v)===network)&&(niche==='all'||v.nicheIds.includes(niche))&&(!search||`${v.title} ${v.channel}`.toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>b.readings.at(-1)!.views-a.readings.at(-1)!.views);
 const breakouts=smallAccountBreakouts(posts,data.creators,breakoutRules,Date.parse(data.generatedAt));
 const socialPosts=posts.filter(v=>videoPlatform(v)!=='youtube');
 const audienceKnown=socialPosts.filter(v=>data.creators.some(c=>c.platform===videoPlatform(v)&&c.handle.toLowerCase()===v.channel.toLowerCase()&&!c.error&&c.followers!==null&&c.observedAt&&Date.parse(data.generatedAt)-Date.parse(c.observedAt)<=24*3600000)).length;
 const latest=data.runs[0];
 const history=data.trends.flatMap(t=>t.history.map(h=>({...h,title:t.title,nicheId:t.nicheId,platform:t.platform}))).filter(h=>(network==='all'||h.platform===network)&&(niche==='all'||h.nicheId===niche)).sort((a,b)=>b.at.localeCompare(a.at)).slice(0,100);
 return <div className="max-w-[1600px] mx-auto space-y-6">
  <header className="flex flex-wrap justify-between items-start gap-4"><div><Link href="/competitors" className="eyebrow hover:underline">Market & Competitors / {business}</Link><h1 className="mt-3 text-3xl font-semibold tracking-tight flex items-center gap-3"><Radio className="text-bb-teal w-8 h-8"/>Trend Radar</h1><p className="text-sm text-bb-muted mt-2">Spot the signals. Follow the momentum. Find your next angle.</p></div>
  <div className="flex flex-wrap gap-2"><Link href="/guides/trend-radar-playbook" className="px-3 py-2.5 rounded-lg border border-bb-border text-bb-fg text-sm hover:border-bb-teal/50">How to use · playbook</Link><button onClick={()=>{setView('accounts');setSettings(false);}} className="px-3 py-2.5 rounded-lg border border-bb-blue/40 text-bb-blue text-sm">Watch accounts</button><button onClick={()=>{setDraft(data.niches);setSettings(!settings);}} className="px-3 py-2.5 rounded-lg border border-bb-border text-sm flex gap-2 items-center"><SlidersHorizontal className="w-4 h-4"/>Manage niches</button><button disabled={busy} onClick={()=>action('scan')} className="px-4 py-2.5 rounded-lg bg-bb-teal/15 border border-bb-teal/40 text-bb-teal text-sm flex gap-2 items-center disabled:opacity-50"><RefreshCw className={`w-4 h-4 ${busy?'animate-spin':''}`}/>{busy?'Scanning…':'Scan now'}</button></div></header>
  {error&&<p role="alert" className="rounded-xl border border-bb-danger/40 bg-bb-danger/10 p-4 text-sm text-bb-danger">{error}</p>}
  {settings&&<section className="card p-5 space-y-4"><h2 className="font-semibold">Discovery niches</h2><p className="text-sm text-bb-muted">Choose up to {MAX_NICHES} niches. Search phrases discover YouTube videos. Instagram and TikTok discover new posts from the public creators you list (up to 12 per niche). Use Watch accounts to add or remove handles and inspect follower counts. Use at least 3 creators per platform to qualify for shared-topic growth signals. Save, then scan to collect the new searches.</p>{draft.map((n,i)=><fieldset key={n.id} className="border border-bb-border rounded-xl p-3 space-y-3"><div className="flex flex-wrap gap-2"><input aria-label={`Niche name ${i+1}`} value={n.name} onChange={e=>setDraft(draft.map((v,j)=>j===i?{...v,name:e.target.value}:v))} className="rounded-lg bg-bb-surface2 border border-bb-border p-2 text-sm"/><input aria-label={`Search phrase ${i+1}`} value={n.query} onChange={e=>setDraft(draft.map((v,j)=>j===i?{...v,query:e.target.value}:v))} className="rounded-lg bg-bb-surface2 border border-bb-border p-2 text-sm flex-1"/><button onClick={()=>setDraft(draft.filter((_,j)=>j!==i))} className="text-xs text-bb-muted">Remove</button></div></fieldset>)}<div className="flex flex-wrap gap-4 text-sm">{DEFAULT_NICHES.filter(p=>!draft.some(n=>n.id===p.id)).map(p=><button key={p.id} disabled={draft.length>=MAX_NICHES} onClick={()=>setDraft([...draft,{...p}])} className="text-bb-blue disabled:opacity-40">+ {p.name}</button>)}<button disabled={draft.length>=MAX_NICHES} onClick={()=>setDraft([...draft,{id:`niche-${Date.now()}`,name:'New niche',query:''}])} className="text-bb-blue disabled:opacity-40">+ Add niche</button><button disabled={busy} onClick={()=>action('configure',draft.map(n=>({...n,instagram:n.instagram?.filter(Boolean),tiktok:n.tiktok?.filter(Boolean)})))} className="text-bb-teal">Save niches</button></div></section>}
  <section className="card p-4 space-y-3"><div className="flex flex-wrap items-center justify-between gap-3 text-xs"><div className="flex flex-wrap gap-4">{data.sources.map(source=><span key={source.platform} className={source.status==='live'?'text-bb-teal':source.configured?'text-bb-warn':'text-bb-dim'}><span className="capitalize">● {source.platform}</span> · {source.status} · {source.posts} posts</span>)}</div><span className="text-bb-muted">{latest?`Last scan ${date(latest.finishedAt)}`:'No scan yet'} · target cadence 15 min</span></div><p className="text-[11px] text-bb-dim">YouTube: niche search. Instagram & TikTok: new posts from your niche creator lists. Public view counts only; missing or hidden counters are never estimated.</p></section>
  {latest?.errors.length? <p className="text-xs text-bb-warn">{latest.errors.join(' · ')}</p>:null}
  <section className="grid grid-cols-2 xl:grid-cols-4 gap-3">{(['Emerging','Breaking out','Established','Fading'] as Stage[]).map(s=><button key={s} onClick={()=>{setView('trends');setStage(stage===s?'all':s);}} className={`card p-5 text-left ${stage===s?'ring-1 ring-bb-blue':''}`}><p className="text-xs text-bb-muted">{s}</p><p className="text-3xl font-semibold mt-2">{data.trends.filter(t=>t.stage===s&&(network==='all'||t.platform===network)&&(niche==='all'||t.nicheId===niche)).length}</p><p className="text-[11px] text-bb-dim mt-2">{s==='Emerging'?'Early measured growth':s==='Breaking out'?'Momentum accelerating':s==='Established'?'Positive signal over 24h':'Measured growth slowing'}</p></button>)}</section>
  <div className="flex flex-wrap gap-2">{[{id:'all',name:'All niches'},...data.niches].map(n=><button key={n.id} onClick={()=>setNiche(n.id)} className={`rounded-full px-4 py-2 text-xs border ${niche===n.id?'border-bb-blue/50 bg-bb-blue/10 text-bb-blue':'border-bb-border text-bb-muted'}`}>{n.name}</button>)}</div>
  <section className="space-y-4"><div className="flex flex-wrap gap-3 items-center justify-between border-b border-bb-border pb-3"><nav className="flex flex-wrap gap-4">{(['trends','posts','top','breakouts','accounts','discovery','feed','history'] as const).map(v=><button key={v} onClick={()=>setView(v)} className={`text-sm pb-2 border-b-2 ${view===v?'text-bb-fg border-bb-teal':'text-bb-muted border-transparent'}`}>{v==='trends'?`Topic signals (${rows.length})`:v==='posts'?`Discovered posts (${posts.length})`:v==='top'?'Top competitor posts':v==='breakouts'?`Small-account breakouts (${breakouts.length})`:v==='accounts'?'Watched accounts':v==='discovery'?'Find competitors':v==='feed'?'Feed discoveries':'Signal history'}</button>)}</nav>{view!=='accounts'&&view!=='discovery'&&view!=='feed'&&<div className="flex flex-wrap gap-2 items-center"><select aria-label="Platform" value={network} onChange={e=>setNetwork(e.target.value)} className="bg-bb-surface2 border border-bb-border rounded-lg p-2 text-xs"><option value="all">All platforms</option>{PLATFORMS.map(p=><option key={p} value={p}>{p==='youtube'?'YouTube':p==='instagram'?'Instagram':'TikTok'}</option>)}</select><Search className="w-4 h-4 text-bb-dim"/><input aria-label="Search trends" placeholder="Find a topic or creator…" value={search} onChange={e=>setSearch(e.target.value)} className="text-sm bg-transparent border border-bb-border rounded-lg px-3 py-2 w-52"/>{view==='trends'&&<select aria-label="Trend stage" value={stage} onChange={e=>setStage(e.target.value)} className="bg-bb-surface2 border border-bb-border rounded-lg px-2 text-xs"><option value="all">All stages</option>{STAGES.map(s=><option key={s}>{s}</option>)}</select>}</div>}</div>
  {view==='feed'&&<FeedDiscoveries niches={data.niches} onWatched={async()=>{const r=await fetch('/api/trends');if(r.ok)setData(await r.json());}}/>}
  {view==='discovery'&&<TrendDiscovery niches={data.niches} onWatched={async()=>{const r=await fetch('/api/trends');if(r.ok)setData(await r.json());}}/>}
  {view==='accounts'&&!settings&&<TrendWatchlist niches={data.niches} creators={data.creators} videos={data.videos} busy={busy} onSave={n=>action('configure',n)}/>}
  {view==='trends'&&<><p className="text-xs text-bb-muted">{data.trends.some(t=>t.measured>=3)?'Signals are heuristic and limited to the monitored sample. Open a topic to inspect its evidence.':'Building the baseline. Live candidates appear below; growth labels need repeat observations at least 12 minutes apart.'} A shared phrase or hashtag suggests a topic; it does not prove a shared format or audio.</p>{rows.length?<div className="grid lg:grid-cols-2 xl:grid-cols-3 gap-4">{rows.map(t=><button key={t.id} onClick={()=>setSelected(t)} className="card card-hover p-5 text-left flex flex-col gap-4"><div className="flex items-center justify-between gap-2"><span className="eyebrow text-[9px]">{data.niches.find(n=>n.id===t.nicheId)?.name} · {t.platform}</span><span className={`rounded-full border px-2.5 py-1 text-[10px] ${tone[t.stage]}`}>{t.stage}</span></div><h3 className="text-xl font-semibold capitalize">{t.title}</h3><div className="grid grid-cols-3 gap-2"><div><p className="text-lg font-semibold">{t.velocity===null?'—':number(t.velocity)}</p><p className="text-[10px] text-bb-dim">new views / hr</p></div><div><p className="text-lg font-semibold">{t.creators}</p><p className="text-[10px] text-bb-dim">creators</p></div><div><p className="text-lg font-semibold">{t.acceleration===null?'—':`${t.acceleration.toFixed(1)}×`}</p><p className="text-[10px] text-bb-dim">acceleration</p></div></div><p className="text-xs text-bb-muted leading-relaxed flex-1">{t.reason}</p><div className="flex items-center justify-between border-t border-bb-border/60 pt-3"><span className="text-[10px] text-bb-dim">{t.videos.length} posts · {number(t.views)} total views</span><span className="text-xs text-bb-blue">Inspect evidence ↗</span></div></button>)}</div>:<div className="card p-10 text-center"><Activity className="mx-auto text-bb-teal mb-3"/><p>No matching topic signals yet.</p><p className="text-sm text-bb-muted mt-2">{data.videos.length?'No shared topic currently meets the evidence rules. Inspect the live posts or try another filter.':'Run a scan to discover recent posts and start measuring.'}</p>{posts.length>0&&<button onClick={()=>setView('posts')} className="mt-4 rounded-lg border border-bb-teal/40 px-4 py-2 text-sm text-bb-teal">View {posts.length} live posts</button>}</div>}</>}
  {view==='top'&&<TopCompetitorPosts videos={posts} creators={data.creators} now={Date.parse(data.generatedAt)}/>}
  {view==='posts'&&<div className="grid lg:grid-cols-2 gap-3">{posts.length?posts.map(v=><div key={v.id} className="card p-3"><Evidence video={v}/><div className="flex items-center justify-between mt-2 px-2"><p className="text-[10px] text-bb-dim">{v.readings.length} saved observations</p><Spark video={v}/></div></div>):<p className="text-sm text-bb-muted">No matching posts. Try a broader search phrase and scan again.</p>}</div>}
  {view==='breakouts'&&<section className="space-y-4">
   <div className="card p-5 space-y-4"><h2 className="text-lg font-semibold">Big reach from a small audience</h2><p className="text-sm text-bb-muted">Find Instagram and TikTok videos whose reach is large relative to their creator’s following. Ranked by views per follower.</p>
    <div className="flex flex-wrap gap-4">{([{key:'maxFollowers',label:'Maximum followers',values:[1000,10000,50000,100000]},{key:'minViews',label:'Minimum video views',values:[10000,100000,1000000]},{key:'minRatio',label:'Minimum views / follower',values:[5,10,20,50]}] as const).map(f=><label key={f.key} className="text-xs text-bb-muted">{f.label}<select aria-label={f.label} value={breakoutRules[f.key]} onChange={e=>setBreakoutRules({...breakoutRules,[f.key]:Number(e.target.value)})} className="block mt-1 bg-bb-surface2 border border-bb-border rounded-lg p-2.5 text-sm">{f.values.map(v=><option key={v} value={v}>{f.key==='minRatio'?`${v}×`:number(v)}</option>)}</select></label>)}</div>
    <p className="text-xs text-bb-dim">{audienceKnown}/{socialPosts.length} matching social posts have a current audience count. Missing, zero or unavailable follower counts are excluded. Followers are measured now, not at publication; views are not unique people. This flags video outliers, not proof that a format is spreading or that reach was organic.</p>
   </div>
   {breakouts.length?<div className="grid lg:grid-cols-2 gap-4">{breakouts.map(({video,creator,ratio,topics})=><article key={video.id} className="card p-4 space-y-3"><div className="flex justify-between gap-3 items-center"><span className="text-xs text-bb-violet">Small-account breakout</span><strong className="text-bb-teal">{number(ratio)}× views / follower</strong></div><Evidence video={video}/><div className="flex flex-wrap gap-4 text-xs"><span>{number(creator.followers!)} followers</span><span>{number(video.readings.at(-1)!.views)} views</span><span className="text-bb-dim">Audience checked {date(creator.observedAt!)}</span></div>{topics.length>0&&<p className="text-xs text-bb-muted">Caption topics to investigate: {topics.join(' · ')}</p>}<Spark video={video}/></article>)}</div>:<div className="card p-8 text-center space-y-3"><Activity className="mx-auto text-bb-violet"/><p>No videos meet these breakout thresholds yet.</p><p className="text-sm text-bb-muted">Add smaller accounts to your watchlist, scan for their public counts, or adjust the filters. Results cover watched accounts only.</p><button onClick={()=>setView('accounts')} className="text-sm text-bb-blue">Choose accounts to watch →</button></div>}
  </section>}
  {view==='history'&&<div className="card p-4 space-y-3"><p className="text-xs text-bb-muted">Observed states over time, newest first. No history is backfilled before the first scan.</p>{history.length?history.map((h,i)=><div key={`${h.id}-${h.at}-${i}`} className="flex flex-wrap gap-4 text-xs border-t border-bb-border/60 pt-3"><span className="text-bb-dim">{date(h.at)}</span><span className="capitalize flex-1">{h.title}</span><span className={tone[h.stage].split(' ')[0]}>{h.stage}</span><span>{h.velocity===null?'Awaiting baseline':`${number(h.velocity)} views/hr`}</span></div>):<p className="text-sm text-bb-muted">History starts when the first shared topic is observed.</p>}</div>}
  </section>
  <details className="card p-4 text-xs text-bb-muted"><summary className="cursor-pointer text-bb-fg">How this radar works · coverage & scan health</summary><div className="mt-3 space-y-3"><p>YouTube videos published within the last 8 days and public Instagram/TikTok videos from the last 30 days enter through YouTube niche searches and Instagram/TikTok creator lists. New-post discovery and saved-post checks target every 15 minutes while the collector and this Mac are running. Up to 240 posts are observed per scan. Search ranking and creator lists are samples, not comprehensive platform coverage. Instagram uses public embeds; TikTok uses public profile listings and video pages. Each platform is limited to 80 observations per scan.</p><p>Topic grouping uses repeated two-word title phrases across at least two channels. An emerging signal requires three growing creators, 70% measured coverage and 1,000 new views/hour. Breaking out needs three comparable histories and 1.5× acceleration. Established needs a prior positive signal at least 24 hours old. Fading needs a prior positive signal and a measured drop exceeding 40%. These are initial thresholds, not calibrated predictions of virality.</p><p>Source counters can lag. Stale, missing or decreasing counters never become negative growth. Small-account breakouts compare public views with a current follower count, separate from the multi-creator trend stages. Audience counts refresh during discovery; counts older than 24 hours and video readings older than 30 minutes are excluded from breakouts. Creator-relative historical baselines and audio matching are not included. Platforms are scored separately so view counters and creator identities are never mixed. Private profiles, login walls and unsupported embeds fail visibly.</p>{data.runs.map(r=><p key={r.at}>{date(r.finishedAt)} · {r.observed} pages read · {r.discovered} search results · {r.errors.length?'partial / failed':'complete'}</p>)}</div></details>
  {selected&&<div className="fixed inset-0 z-50 bg-black/70 flex justify-end" onClick={()=>setSelected(null)}><section ref={dialog} role="dialog" aria-modal="true" aria-label={`Evidence for ${selected.title}`} onClick={e=>e.stopPropagation()} className="w-full max-w-2xl bg-[#0e1424] border-l border-bb-border p-6 overflow-y-auto"><button autoFocus onClick={()=>setSelected(null)} className="float-right text-sm text-bb-blue">Close ✕</button><p className="eyebrow">Topic evidence</p><h2 className="text-2xl font-semibold capitalize mt-3">{selected.title}</h2><p className="text-sm text-bb-muted mt-3">{selected.reason}</p><p className="text-xs text-bb-dim mt-2">First spotted {date(selected.firstSeen)} · {selected.measured}/{selected.videos.length} posts have measured growth.</p><div className="mt-6 space-y-4">{selected.videos.map(v=><div key={v.id}><Evidence video={v}/><div className="mt-2 flex items-center justify-between"><span className="text-xs text-bb-dim">{v.readings.length} observations</span><Spark video={v}/></div></div>)}</div></section></div>}
 </div>;
}
