'use client';
import {useEffect,useState} from 'react';
import ReactMarkdown from 'react-markdown';
import type {Niche,SocialPlatform} from '@/lib/trends';
import type {DiscoverySchedule} from '@/lib/trend-automation';
import type {DiscoveryRun} from '@/lib/trend-discovery';
export default function TrendDiscovery({niches,onWatched}:{niches:Niche[];onWatched:()=>Promise<void>}) {
 const [runs,setRuns]=useState<DiscoveryRun[]>([]),[seed,setSeed]=useState(''),[platform,setPlatform]=useState<SocialPlatform>('instagram'),[niche,setNiche]=useState(niches[0]?.id??''),[focus,setFocus]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Record<string,string[]>>({}),[notice,setNotice]=useState('');
 const [schedules,setSchedules]=useState<DiscoverySchedule[]>([]),[hours,setHours]=useState(24),[autoWatch,setAutoWatch]=useState(true),[defaults,setDefaults]=useState<{focus:string;seeds:Record<string,string>}|null>(null);
 async function refresh(){const r=await fetch('/api/trend-discovery');if(!r.ok)throw Error('Could not load discovery history.');const d=await r.json();setRuns(d.runs);setSchedules(d.schedules??[]);setDefaults(d.defaults??null);}
 useEffect(()=>{refresh().catch(e=>setError(e.message));},[]);
 const running=runs.some(r=>r.status==='running');
 useEffect(()=>{if(!running)return;const t=setInterval(()=>refresh().catch(e=>setError(e.message)),3000);return()=>clearInterval(t);},[running]);
 async function action(body:object){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/trend-discovery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);setRuns(d.runs);setSchedules(d.schedules??[]);return true;}catch(e){setError(e instanceof Error?e.message:'Request failed');return false;}finally{setBusy(false);}}
 async function watch(run:DiscoveryRun){if(await action({action:'watch',id:run.id,handles:selected[run.id]??[]})){await onWatched();setSelected({...selected,[run.id]:[]});setNotice('Selected accounts added to your watchlist. Scan now to start tracking their posts.');}}
 return <section className="space-y-4" aria-label="Competitor discovery">
  <form onSubmit={e=>{e.preventDefault();void action({action:'discover',seed,platform,nicheId:niche,focus});}} className="card p-5 space-y-4"><h2 className="text-lg font-semibold">Find competitors from an account</h2><p className="text-sm text-bb-muted">Paste your account or a known competitor. HQ researches their offering and audience, then finds similar accounts with evidence for each match.</p>
   <div className="grid md:grid-cols-2 gap-3"><label className="text-xs text-bb-muted">Seed account<input aria-label="Discovery seed account" required value={seed} onChange={e=>setSeed(e.target.value)} placeholder="@account or Instagram / TikTok profile URL" className="block w-full mt-1 bg-bb-surface2 rounded-lg border border-bb-border p-2.5 text-sm"/></label><label className="text-xs text-bb-muted">Platform<select aria-label="Discovery platform" value={platform} onChange={e=>setPlatform(e.target.value as SocialPlatform)} className="block w-full mt-1 bg-bb-surface2 rounded-lg border border-bb-border p-2.5 text-sm"><option value="instagram">Instagram</option><option value="tiktok">TikTok</option></select></label>
   <label className="text-xs text-bb-muted">Save selected accounts to<select aria-label="Discovery niche" value={niche} onChange={e=>setNiche(e.target.value)} className="block w-full mt-1 bg-bb-surface2 rounded-lg border border-bb-border p-2.5 text-sm">{niches.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><label className="text-xs text-bb-muted">Competitor focus (optional)<input aria-label="Competitor focus" maxLength={300} value={focus} onChange={e=>setFocus(e.target.value)} placeholder="e.g. Australian vodka water brands" className="block w-full mt-1 bg-bb-surface2 rounded-lg border border-bb-border p-2.5 text-sm"/></label></div>
   <button type="submit" disabled={busy||running||!seed.trim()} className="text-sm rounded-lg px-4 py-2.5 bg-bb-violet/15 border border-bb-violet/40 text-bb-violet disabled:opacity-40">{running?'Researching competitors…':'Find competitors'}</button><p className="text-xs text-bb-dim">Usually a few minutes. Uses your installed research runtime and its usage allowance. Suggestions are potential competitors; review the evidence before adding. Manual searches require selecting accounts. Scheduled searches can automatically watch eligible direct competitors.</p>
  </form>
  <section aria-label="Automatic competitor discovery" className="card p-5 space-y-3"><h2 className="text-lg font-semibold">Automatic competitor discovery</h2><p className="text-sm text-bb-muted">Use the seed, platform, niche and focus above. Runs for this business while HQ’s collector and this Mac are running, even with the browser closed.</p>
   <button type="button" disabled={!defaults?.seeds[platform]} onClick={()=>{setSeed(defaults?.seeds[platform]??'');setFocus(defaults?.focus??'');}} className="text-sm text-bb-blue disabled:opacity-40">Use this business’s saved {platform} account and context</button>
   <div className="flex flex-wrap gap-3"><label className="text-sm">Search frequency<select aria-label="Discovery frequency" value={hours} onChange={e=>setHours(Number(e.target.value))} className="block bg-bb-surface2 border border-bb-border p-2 rounded-lg"><option value={24}>Daily</option><option value={168}>Weekly</option></select></label><label className="text-sm">New accounts<select aria-label="Automatic watch mode" value={String(autoWatch)} onChange={e=>setAutoWatch(e.target.value==='true')} className="block bg-bb-surface2 border border-bb-border p-2 rounded-lg"><option value="true">Auto-watch verified direct competitors</option><option value="false">Suggestions only</option></select></label></div>
   <p className="text-xs text-bb-dim">Auto-watch requires an official website social link, a readable public profile and a direct-competitor match. Other matches remain suggestions. Up to 12 accounts per niche/platform. Uses your existing research allowance.</p>
   <button disabled={busy||!seed.trim()} onClick={async()=>{if(await action({action:'schedule',seed,platform,nicheId:niche,focus,hours,autoWatch,enabled:true}))setNotice('Automatic discovery enabled. First run starts on a collector tick; scheduled posts scans continue every 15 minutes.');}} className="text-sm text-bb-teal disabled:opacity-40">Enable automatic discovery with these settings</button>
   {schedules.map(s=><div key={s.id} className="border-t border-bb-border pt-3 text-sm space-y-2"><p>@{s.seed} · {s.platform} · {niches.find(n=>n.id===s.nicheId)?.name??'Removed niche'} · {s.hours===24?'Daily':'Weekly'} · {s.autoWatch?'Auto-watch':'Suggestions only'} · {s.enabled?'Enabled':'Paused'}</p><p className="text-xs text-bb-muted">{s.lastAttempt?`Last attempted ${new Date(s.lastAttempt).toLocaleString('en-AU')}`:'Awaiting first collector tick'}{s.enabled&&s.lastAttempt?` · Next due ${new Date(Date.parse(s.lastAttempt)+s.hours*3600000).toLocaleString('en-AU')}`:''}</p>{s.error&&<p className="text-xs text-bb-warn">{s.error}</p>}<button onClick={()=>void action({action:'toggle-schedule',id:s.id,enabled:!s.enabled})} disabled={busy} className="text-bb-blue">{s.enabled?'Pause':'Resume'} automatic discovery for @{s.seed}</button></div>)}
  </section>
  {error&&<p role="alert" className="text-sm text-bb-danger">{error}</p>}{notice&&<p role="status" className="text-sm text-bb-teal">{notice}</p>}
  {runs.map(run=><section key={run.id} className="card p-5 space-y-4"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">Similar to @{run.seed}</h3><p className="text-xs text-bb-muted mt-1">{run.platform} · {niches.find(n=>n.id===run.nicheId)?.name??'Removed niche'} · {new Date(run.at).toLocaleString('en-AU')}</p></div><span className="text-xs text-bb-muted">{run.status==='running'?'Searching and checking profiles…':run.status==='failed'?'Could not complete':`${run.candidates.length} suggestions`}</span></div>
   {run.status!=='running'&&<button disabled={busy||running} onClick={()=>void action({action:'discover',seed:run.seed,platform:run.platform,nicheId:run.nicheId,focus:run.focus.slice(0,300)})} className="text-sm text-bb-blue disabled:opacity-40">Find more accounts like @{run.seed}</button>}
   {run.error&&<p className="text-sm text-bb-warn">{run.error}</p>}{run.summary&&<div className="text-sm text-bb-muted"><ReactMarkdown components={{a:({children,href})=><a href={href} target="_blank" rel="noreferrer" className="text-bb-blue underline">{children}</a>}}>{run.summary}</ReactMarkdown></div>}
   <div className="grid lg:grid-cols-2 gap-3">{run.candidates.map(c=>{const watched=(niches.find(n=>n.id===run.nicheId)?.[run.platform]??[]).includes(c.handle);return <label key={c.handle} className="border border-bb-border rounded-xl p-4 space-y-2 block"><div className="flex gap-3 items-start"><input aria-label={`Select ${c.handle} from ${run.seed}`} type="checkbox" disabled={watched||busy} checked={watched||(selected[run.id]??[]).includes(c.handle)} onChange={e=>setSelected({...selected,[run.id]:e.target.checked?[...(selected[run.id]??[]),c.handle]:(selected[run.id]??[]).filter(h=>h!==c.handle)})} className="mt-1"/><div><a href={c.url} target="_blank" rel="noreferrer" className="text-bb-blue text-sm">{c.name} · @{c.handle} ↗</a><p className="text-xs text-bb-dim mt-1">{watched?'Already watched':c.profileChecked?'Public profile checked':'Search evidence; public profile unavailable'}{c.followers!==null?` · ${c.followers.toLocaleString()} followers`:''}</p></div></div><p className="text-sm text-bb-muted">{c.reason}</p><a href={c.evidence} target="_blank" rel="noreferrer" className="text-xs text-bb-blue inline-block">View match evidence ↗</a></label>;})}</div>
   {run.status==='complete'&&run.candidates.length>0&&<button disabled={busy||!(selected[run.id]??[]).length} onClick={()=>watch(run)} className="rounded-lg px-4 py-2 text-sm text-bb-teal border border-bb-teal/40 disabled:opacity-40">Watch selected ({(selected[run.id]??[]).length})</button>}
   {run.status==='complete'&&!run.candidates.length&&<p className="text-sm text-bb-muted">No supported matches found. Try a clearer competitor focus or another seed account.</p>}
  </section>)}
 </section>;
}
