import fs from 'node:fs';
import path from 'node:path';
import {randomBytes,randomUUID,createHash,timingSafeEqual} from 'node:crypto';
import {trendDir,readNiches,saveNiches} from './trend-store';
import {writePrivateJson} from './private-adapter';
import {getProfile,listBusinesses} from './store';
import {MAX_WATCHED_ACCOUNTS,type SocialPlatform} from './trends';
import {observeSocial} from './trend-social-source';
export type FeedSession={id:string;platform:SocialPlatform;nicheId:string;maxPosts:number;minutes:number;createdAt:string;startedAt?:string;lastSeen?:string;status:'waiting'|'running'|'stopped'|'complete'|'expired'|'error';reason?:string;collected:string[];pairHash?:string;tokenHash?:string};
export type FeedPost={id:string;platform:SocialPlatform;url:string;handle:string;caption:string;nicheId:string;sessionIds:string[];firstSeen:string;lastSeen:string;visible:{views?:string;likes?:string;comments?:string};verified?:{views:number;at:string;publishedAt:string|null};checkError?:string;checkedAt?:string};
type Store={sessions:FeedSession[];posts:FeedPost[]};
const file=(slug:string)=>path.join(trendDir(slug),'feed.json');
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
function equal(a:string|undefined,b:string){return !!a&&a.length===64&&timingSafeEqual(Buffer.from(a,'hex'),Buffer.from(hash(b),'hex'));}
export function readFeed(slug:string):Store {const f=file(slug);const state:Store=fs.existsSync(f)?JSON.parse(fs.readFileSync(f,'utf8')):{sessions:[],posts:[]};for(const s of state.sessions){if(s.status==='waiting'&&Date.now()-Date.parse(s.createdAt)>10*60000){s.status='expired';s.reason='Session start window expired';}if(s.status==='running'&&s.startedAt&&Date.now()-Date.parse(s.startedAt)>s.minutes*60000){s.status='complete';s.reason='Time limit reached';}}return state;}
function save(slug:string,s:Store){fs.mkdirSync(trendDir(slug),{recursive:true});writePrivateJson(file(slug),{sessions:s.sessions.slice(0,50),posts:s.posts.slice(0,2000)});}
export function feedView(slug:string){const s=readFeed(slug);return {sessions:s.sessions.map(({pairHash,tokenHash,...publicSession})=>publicSession),posts:s.posts};}
export function createFeedSession(slug:string,raw:unknown){const v=raw as Record<string,unknown>;
 if(!v||!['instagram','tiktok'].includes(String(v.platform))||typeof v.nicheId!=='string'||!readNiches(slug).some(n=>n.id===v.nicheId)||![10,25,50,100].includes(Number(v.maxPosts))||![2,5,10].includes(Number(v.minutes)))throw Error('Choose a platform, saved niche and session limits.');
 const state=readFeed(slug);if(state.sessions.some(s=>['waiting','running'].includes(s.status)))throw Error('Stop the existing feed session first.');
 const secret=randomBytes(24).toString('base64url'),s:FeedSession={id:randomUUID(),platform:v.platform as SocialPlatform,nicheId:v.nicheId,maxPosts:Number(v.maxPosts),minutes:Number(v.minutes),createdAt:new Date().toISOString(),status:'waiting',collected:[],pairHash:hash(secret)};state.sessions.unshift(s);save(slug,state);return {code:`${slug}.${s.id}.${secret}`,sessionId:s.id};
}
export function pairFeed(code:unknown,platform:unknown){if(typeof code!=='string'||code.length>200)throw Error('Invalid pairing code');const [slug,id,secret,...extra]=code.split('.');if(extra.length||!secret||!/^[a-z0-9-]{1,80}$/.test(slug)||!getProfile(slug))throw Error('Invalid pairing code');const state=readFeed(slug),s=state.sessions.find(s=>s.id===id);if(!s||s.status!=='waiting'||s.platform!==platform||!equal(s.pairHash,secret))throw Error('Code expired, already used, or wrong platform');const token=randomBytes(32).toString('base64url');s.tokenHash=hash(token);delete s.pairHash;s.status='running';s.startedAt=new Date().toISOString();s.lastSeen=s.startedAt;save(slug,state);return {slug,id,token,platform:s.platform,maxPosts:s.maxPosts,minutes:s.minutes,startedAt:s.startedAt};}
// Only exposed through the extension-origin bridge. The user must first arm a
// bounded session in HQ, then explicitly select/start it in the extension.
export function pendingFeeds(platform:unknown){
 if(!['instagram','tiktok'].includes(String(platform)))throw Error('Choose a supported feed');
 return listBusinesses().profiles.flatMap(p=>readFeed(p.slug).sessions.filter(s=>s.status==='waiting'&&s.platform===platform).map(s=>({slug:p.slug,id:s.id,business:p.name,niche:readNiches(p.slug).find(n=>n.id===s.nicheId)?.name??s.nicheId,platform:s.platform,minutes:s.minutes,maxPosts:s.maxPosts})));
}
export function connectFeed(slug:unknown,id:unknown,platform:unknown){
 const pending=pendingFeeds(platform).find(s=>s.slug===slug&&s.id===id);
 if(!pending)throw Error('Session expired or already started. Create a new session in HQ.');
 const state=readFeed(pending.slug),s=state.sessions.find(s=>s.id===id)!;
 const secret=randomBytes(24).toString('base64url');s.pairHash=hash(secret);save(pending.slug,state);
 return pairFeed(`${pending.slug}.${s.id}.${secret}`,platform);
}
export function canonicalFeedPost(raw:unknown,platform:SocialPlatform){const v=raw as Record<string,unknown>;if(!v||typeof v.url!=='string'||v.url.length>500)throw Error('Invalid post');const u=new URL(v.url);if(u.protocol!=='https:'||u.port||u.username||u.password)throw Error('Invalid post URL');let id:string,handle='';if(platform==='instagram'){if(!['instagram.com','www.instagram.com'].includes(u.hostname))throw Error('Wrong platform');const m=u.pathname.match(/^\/(?:(?:[\w.]+)\/)?(reel|reels|p)\/([\w-]{5,40})\/?$/);if(!m)throw Error('Not an Instagram post');id=`instagram:${m[2]}`;u.pathname=`/${m[1]==='p'?'p':'reel'}/${m[2]}/`;handle=typeof v.handle==='string'?v.handle.replace(/^@/,'').toLowerCase():'';}else{if(!['tiktok.com','www.tiktok.com'].includes(u.hostname))throw Error('Wrong platform');const m=u.pathname.match(/^\/@([\w.]{1,40})\/video\/(\d{10,30})\/?$/);if(!m)throw Error('Not a TikTok post');handle=m[1].toLowerCase();id=`tiktok:${m[2]}`;}if(handle&&!/^[a-z0-9._]{1,40}$/.test(handle))throw Error('Invalid handle');u.search='';u.hash='';u.hostname=`www.${platform}.com`;const visible:FeedPost['visible']={};for(const key of ['views','likes','comments'] as const){const metric=(v.visible as Record<string,unknown>|undefined)?.[key];if(typeof metric==='string'&&metric.length<=50&&/\d/.test(metric))visible[key]=metric;}return {id,platform,url:u.toString(),handle,caption:typeof v.caption==='string'?v.caption.slice(0,2000):'',visible};}
export function ingestFeed(slug:string,id:string,token:string,raw:unknown){const state=readFeed(slug),s=state.sessions.find(s=>s.id===id);if(!s||!equal(s.tokenHash,token))throw Error('Invalid session');if(s.status!=='running'){save(slug,state);return {stop:true,status:s.status,count:s.collected.length,reason:s.reason};}
 const v=raw as {posts?:unknown;stop?:unknown;reason?:unknown};if(!v||!Array.isArray(v.posts)||v.posts.length>10)throw Error('Send up to 10 visible posts per batch');let rejected=0;
 for(const rawPost of v.posts){if(s.collected.length>=s.maxPosts)break;try{const incoming=canonicalFeedPost(rawPost,s.platform),at=new Date().toISOString();let post=state.posts.find(p=>p.id===incoming.id);if(!s.collected.includes(incoming.id))s.collected.push(incoming.id);if(post){Object.assign(post,{...incoming,handle:incoming.handle||post.handle,caption:incoming.caption||post.caption,visible:{...post.visible,...incoming.visible},lastSeen:at,sessionIds:[...new Set([...post.sessionIds,s.id])].slice(-20)});}else{post={...incoming,nicheId:s.nicheId,sessionIds:[s.id],firstSeen:at,lastSeen:at};state.posts.unshift(post);}}catch{rejected++;}}
 s.lastSeen=new Date().toISOString();if(v.stop===true){s.status='stopped';s.reason=typeof v.reason==='string'?v.reason.slice(0,150):'Stopped in browser';}else if(s.collected.length>=s.maxPosts){s.status='complete';s.reason='Post limit reached';}save(slug,state);return {stop:s.status!=='running',status:s.status,count:s.collected.length,rejected,reason:s.reason};
}
export function stopFeed(slug:string,id:string){const state=readFeed(slug),s=state.sessions.find(s=>s.id===id);if(!s)throw Error('Unknown session');if(['waiting','running'].includes(s.status)){s.status='stopped';s.reason='Stopped in HQ';delete s.pairHash;}save(slug,state);}
export function watchFeedAccount(slug:string,id:string){const post=readFeed(slug).posts.find(p=>p.id===id);if(!post?.handle)throw Error('No readable creator handle');const niches=readNiches(slug),n=niches.find(n=>n.id===post.nicheId);if(!n)throw Error('Niche removed');const handles=[...new Set([...(n[post.platform]??[]),post.handle])];if(handles.length>MAX_WATCHED_ACCOUNTS)throw Error('Watchlist full; remove an account first');n[post.platform]=handles;saveNiches(slug,niches);}
export async function refreshFeed(slug:string,observer=observeSocial){const rows=readFeed(slug).posts.filter(p=>!p.checkedAt||Date.now()-Date.parse(p.checkedAt)>15*60000).sort((a,b)=>(a.checkedAt??'').localeCompare(b.checkedAt??'')).slice(0,10);const updates=await Promise.all(rows.map(async p=>{try{const v=await observer({id:p.id,platform:p.platform,url:p.url,channel:p.handle});return {id:p.id,handle:p.handle||v.channel,caption:p.caption||v.title,verified:{views:v.readings.at(-1)!.views,at:v.readings.at(-1)!.at,publishedAt:v.publishedAt},checkedAt:new Date().toISOString(),checkError:undefined};}catch{return {id:p.id,checkedAt:new Date().toISOString(),checkError:'Public view count unavailable; visible feed metrics retained.'};}}));const state=readFeed(slug);for(const u of updates){const p=state.posts.find(p=>p.id===u.id);if(p)Object.assign(p,u);}save(slug,state);}
export async function refreshAllFeeds(){for(const p of listBusinesses().profiles)if(fs.existsSync(file(p.slug)))try{await refreshFeed(p.slug);}catch{console.error(`Feed verification unavailable for ${p.slug}`);}}
