// How the departments work together: the hand-offs between them (the web), the loops those
// hand-offs form, and the cross-department workflows that get customers, keep them and grow
// what they pay. Pure data, client-safe. Department ids are registry slugs plus "ceo".
// Examples stay generic: the framework never names a real business (tests/registry.test.ts).

export type Lever = "get" | "keep" | "expand" | "base";
export type Node = string; // a registry slug, or "ceo"

export const LEVERS: Record<Lever, { name: string; short: string; blurb: string }> = {
  get: { name: "Get customers", short: "Get", blurb: "Find demand, win attention, convert it." },
  keep: { name: "Keep customers", short: "Keep", blurb: "Activate fast, deliver value, catch churn early." },
  expand: { name: "Expand revenue", short: "Expand", blurb: "Upgrades, add-ons, annual plans, teams." },
  base: { name: "Foundation", short: "Foundation", blurb: "Claims, budget, uptime, measurement, follow-through." },
};

/** The ring, in an order that keeps related departments next to each other; the CEO sits in the middle. */
export const NODES: Node[] = [
  "content", "seo", "ads", "design", "sales", "competitors", "engineering", "data",
  "support", "email", "finance", "legal", "security", "people", "operations", "ceo",
];

export type Edge = { from: Node; to: Node; signal: string; levers: Lever[] };
const e = (from: Node, to: Node, signal: string, levers: Lever[]): Edge => ({ from, to, signal, levers });

export const EDGES: Edge[] = [
  e("competitors", "engineering", "Rival shipped a feature, entered a new market or changed pricing", ["keep", "expand"]),
  e("competitors", "content", "Rival posts and hooks that are working", ["get"]),
  e("competitors", "seo", "Rival pages that rank and the keywords they win", ["get"]),
  e("competitors", "ads", "Rival ads running now (ad libraries)", ["get"]),
  e("competitors", "finance", "Rival prices, plans and discounts", ["keep", "expand"]),
  e("competitors", "sales", "Partners and affiliates rivals use", ["get"]),
  e("competitors", "legal", "Rival claims that may break ad rules", ["base"]),
  e("competitors", "ceo", "Weekly competitor brief", ["get", "keep", "expand"]),
  e("support", "engineering", "Top complaints and feature requests, ranked", ["keep", "expand"]),
  e("support", "content", "Questions customers keep asking", ["keep", "get"]),
  e("support", "email", "Where new users get stuck", ["keep"]),
  e("support", "data", "Tagged tickets and cancel reasons", ["keep"]),
  e("support", "sales", "Customers asking for more (seats, API, higher tier)", ["expand"]),
  e("support", "design", "Screens people find confusing", ["keep"]),
  e("support", "security", "Suspicious logins and account takeovers", ["base"]),
  e("support", "legal", "Complaints with legal risk (refunds, vulnerable customers)", ["base"]),
  e("support", "competitors", "Customers mentioning a rival", ["keep"]),
  e("data", "email", "At-risk, inactive and ready-to-upgrade segments", ["keep", "expand"]),
  e("data", "engineering", "Funnel drop-offs and feature usage", ["get", "keep", "expand"]),
  e("data", "ads", "Cost to win and conversion by channel", ["get"]),
  e("data", "finance", "MRR, churn and lifetime value by tier", ["get", "keep", "expand"]),
  e("data", "content", "Which posts and hooks drove sign-ups", ["get"]),
  e("data", "sales", "Which partners bring customers who stay", ["get"]),
  e("data", "support", "High-value customers going quiet", ["keep"]),
  e("data", "ceo", "Weekly growth scorecard", ["get", "keep", "expand"]),
  e("engineering", "content", "What shipped and why it matters", ["keep", "get"]),
  e("engineering", "email", "Launches and feature announcements", ["keep", "expand"]),
  e("engineering", "support", "Release notes and known issues", ["keep"]),
  e("engineering", "data", "Tracking events for new features", ["base"]),
  e("engineering", "sales", "Partner features: referral codes, API, white-label", ["get", "expand"]),
  e("content", "seo", "Videos and articles to rank", ["get"]),
  e("content", "ads", "Proven organic winners to boost", ["get"]),
  e("content", "email", "Tutorials and stories for sequences", ["keep"]),
  e("content", "support", "Help videos to link in answers", ["keep"]),
  e("content", "sales", "Partner kit and demo clips", ["get"]),
  e("content", "legal", "Posts with claims to check before publishing", ["base"]),
  e("seo", "content", "What people search for, with volume", ["get"]),
  e("seo", "engineering", "Pages to generate at scale (item, category, comparison)", ["get"]),
  e("seo", "data", "Search traffic and rankings", ["get"]),
  e("ads", "data", "Spend and results per campaign", ["get"]),
  e("ads", "design", "Landing page variants to test", ["get"]),
  e("email", "data", "Opens, clicks and conversions per sequence", ["keep", "expand"]),
  e("email", "support", "Customer replies to emails", ["keep"]),
  e("email", "sales", "Leads who engaged but didn't buy", ["get"]),
  e("sales", "engineering", "What partners and big customers need", ["expand", "get"]),
  e("sales", "finance", "Commissions and deal terms", ["get", "expand"]),
  e("sales", "legal", "Partner contracts to review", ["base"]),
  e("sales", "content", "Co-marketing slots with partners", ["get"]),
  e("sales", "data", "Partner and referral codes to attribute", ["get"]),
  e("finance", "ads", "Budget cap set by payback period", ["get"]),
  e("finance", "engineering", "Pricing and tier rules", ["expand"]),
  e("finance", "email", "Failed payments and renewals due", ["keep"]),
  e("finance", "ceo", "Cash runway and margin", ["base"]),
  e("design", "content", "Brand kit and templates", ["get"]),
  e("design", "engineering", "Onboarding, upgrade and cancel screens", ["keep", "expand"]),
  e("legal", "content", "What we may and may not claim", ["base"]),
  e("legal", "ads", "Ad rules per platform and region", ["base"]),
  e("legal", "email", "Consent and unsubscribe rules", ["base"]),
  e("legal", "engineering", "Privacy, age and regulated-industry requirements", ["base"]),
  e("security", "engineering", "Incidents, stale data and vulnerabilities", ["keep"]),
  e("security", "support", "Outage notice before customers notice", ["keep"]),
  e("ceo", "operations", "Decisions, owners and deadlines", ["base"]),
  e("operations", "people", "Roles the work now needs", ["base"]),
  e("people", "operations", "Who has capacity; new hires to onboard", ["base"]),
  e("operations", "ceo", "What got done and what slipped", ["base"]),
];

export type Step = [Node, string];
export type Loop = { title: string; levers: Lever[]; blurb: string; steps: Step[]; closes: string };

export const LOOPS: Loop[] = [
  { title: "The insight loop", levers: ["keep", "expand"],
    blurb: "What customers and rivals reveal becomes the roadmap. This is how Market & Competitors keeps customers: it feeds what gets built.",
    steps: [["support", "complaints and requests"], ["competitors", "rival moves"], ["data", "usage and churn reasons"], ["engineering", "decides and builds"], ["content", "shows it"], ["email", "tells the right segment"]],
    closes: "Closes when Support hears whether the change fixed the problem, and Data sees churn move for the people who asked." },
  { title: "The acquisition engine", levers: ["get"],
    blurb: "Demand is found, met with content, amplified where it already works, and converted.",
    steps: [["seo", "finds demand"], ["competitors", "finds gaps"], ["content", "makes it"], ["ads", "boosts the winners"], ["design", "converts the visit"], ["engineering", "activates the sign-up"], ["data", "attributes the customer"]],
    closes: "Closes when Data tells Content which hooks and topics brought customers who stayed, not just clicks." },
  { title: "The retention loop", levers: ["keep"],
    blurb: "Risk is spotted early, someone intervenes, and the root cause gets fixed so it stops recurring.",
    steps: [["data", "flags at-risk customers"], ["email", "nudges"], ["support", "reaches out to high value"], ["engineering", "fixes the cause"], ["security", "keeps data fresh and up"]],
    closes: "Closes when Data compares churn of flagged customers who got help against those who didn't." },
  { title: "The expansion loop", levers: ["expand"],
    blurb: "Customers who outgrow their plan are found and offered the next step at the moment they need it.",
    steps: [["data", "spots limits being hit"], ["engineering", "shows the upgrade in context"], ["finance", "sets the price and offer"], ["email", "follows up"], ["sales", "handles teams and B2B"]],
    closes: "Closes when Finance sees net revenue retention move and adjusts what sits in each tier." },
  { title: "The proof flywheel", levers: ["get", "keep"],
    blurb: "Happy customers become the best marketing, and being featured makes them stay.",
    steps: [["support", "spots a win and asks permission"], ["legal", "checks the claim"], ["content", "tells the story"], ["ads", "uses it as creative"], ["sales", "adds it to the partner kit"]],
    closes: "Closes when new customers who came through proof join the community and produce the next story." },
  { title: "The guard rails", levers: ["base"],
    blurb: "Every loop runs inside the same limits: what we may say, what we can afford, what must stay up, and who follows through.",
    steps: [["legal", "claims and consent"], ["finance", "budget and payback"], ["security", "uptime and accounts"], ["operations", "owners and deadlines"], ["people", "capacity"]],
    closes: "Closes in the weekly CEO review, where a broken guard rail outranks any growth task." },
];

/** metricId: the scorecard number that measures it, when the catalogue has one (lib/scorecard-metrics.ts). */
export type Workflow = { title: string; levers: Lever[]; owner: Node; trigger: string; steps: Step[]; metric: string; example: string; metricId?: string };

export const WORKFLOWS: Workflow[] = [
  // ---------------- Get customers
  { title: "Competitor gap becomes comparison content", levers: ["get"], owner: "content",
    trigger: "Market & Competitors finds a rival weakness, outage or price rise.",
    steps: [["competitors", "Flags the gap with evidence links"], ["seo", "Picks the comparison searches (\"X vs Y\", \"X alternative\")"], ["content", "Makes a comparison video and article"], ["legal", "Checks every claim can be proved"], ["design", "Builds a comparison landing page"], ["ads", "Targets the rival's audience"], ["data", "Tracks sign-ups from the page"]],
    metric: "Sign-ups from comparison pages", example: "Subscription app: a rival raises its price, and a \"cheaper alternative\" page and video are live within a week." },
  { title: "Search demand becomes pages at scale", metricId: "new_signups", levers: ["get"], owner: "seo",
    trigger: "SEO finds a search pattern that repeats across many items.",
    steps: [["seo", "Finds the pattern and its volume"], ["engineering", "Generates one page per item from live data"], ["design", "Makes one strong template"], ["content", "Writes the intro per category"], ["legal", "Adds required notices for regulated industries"], ["data", "Tracks indexing and sign-ups per page type"]],
    metric: "Organic sign-ups", example: "Sports data: a best-odds page for every game. Children's books: a page per reading age and theme." },
  { title: "Self post", levers: ["get"], owner: "content",
    trigger: "The owner has something to say on camera (a series day, a launch, a lesson).",
    steps: [["competitors", "Finds the niche's winning clips with /hq:style: topics, hooks, edit style, pace targets"], ["content", "Scripts it with /hq:script: written for a stranger, cold-reader tested, hq script-check, no dashes"], ["content", "Owner records it on the teleprompter, one take per section"], ["content", "Claude edits it with /hq:self-post: /hq:edit, HyperFrames cards, screen recordings, captions, speed"], ["legal", "Checks claims and every screenshot for other people's names"], ["content", "Owner reviews on the review page; Claude fixes the notes"], ["design", "Makes the cover inside the grid crop"], ["content", "Writes the caption with /ig-caption, then caption-check"], ["ceo", "Says yes to posting"], ["content", "Posts with /hq:publish: feed or trial reels, TikTok, Shorts"], ["support", "Runs a keyword campaign scoped to that one post"], ["data", "Reports which hooks drove follows and link clicks (/ig-audit)"]],
    metric: "Follows and link clicks per post", example: "A founder's daily series: script, one read on the teleprompter, and a finished, captioned Reel with its own keyword campaign the same day." },
  { title: "Clip engine", levers: ["get"], owner: "content",
    trigger: "A long recording exists (teleprompter take, podcast, live stream).",
    steps: [["content", "Records the long piece"], ["content", "Cuts shorts with /hq:clip"], ["legal", "Checks claims in captions"], ["content", "Posts with /hq:publish after the owner's yes"], ["data", "Reports which hooks drove follows and link clicks"], ["content", "Reuses the winning hook formats"], ["ads", "Boosts the top 10% with budget"]],
    metric: "Follows and link clicks per clip", example: "Founder video series: one long video becomes five clips, then hooks are tested with trial reels." },
  { title: "Walkthrough videos in the owner's voice", levers: ["keep", "get"], owner: "content",
    trigger: "A page ships or changes, or a page has no \"How it works\" video.",
    steps: [["content", "Records a clean voice reference on the teleprompter (once)"], ["content", "Clones the owner's voice locally with VoxCPM2 in VoiceStudio (once), and the owner approves it by ear"], ["engineering", "Lists the pages changed since their video, and new pages with none"], ["content", "Scripts each page and records the live site with /hq:walkthrough"], ["legal", "Checks the narration claims nothing the page can't back"], ["content", "Checks every line against its script"], ["ceo", "Watches them and approves"], ["engineering", "Ships them behind each page's How it works button"], ["support", "Links the page's video in answers about it"]],
    metric: "Pages with a current walkthrough, and plays per page", example: "A web app's 17 \"How it works\" videos re-recorded in the founder's own voice in an evening, at no cost per line." },
  { title: "Comment-keyword funnel", levers: ["get"], owner: "email",
    trigger: "A post asks viewers to comment a keyword.",
    steps: [["content", "Posts with one keyword ask"], ["support", "Auto-DMs the link after a follow"], ["email", "Captures the email address with consent"], ["email", "Runs a three-email nurture"], ["engineering", "Offers the free tool or trial"], ["data", "Tracks keyword to email to sign-up"]],
    metric: "DM-to-email and email-to-trial rates", example: "Founder video series: comment a keyword to get the link." },
  { title: "Partner program", levers: ["get"], owner: "sales",
    trigger: "Weekly partner search, or a partner applies.",
    steps: [["sales", "Finds creators, affiliates, podcasts and newsletters"], ["data", "Checks audience fit and overlap"], ["finance", "Sets commission within the payback limit"], ["legal", "Writes partner terms and ad rules"], ["engineering", "Issues referral codes and tracking"], ["design", "Makes the partner kit"], ["content", "Co-creates content"], ["data", "Attributes customers and their 90-day retention"], ["finance", "Pays out monthly"]],
    metric: "Partner-sourced customers still paying at day 90", example: "Sports data: creators with a promo code. Children's books: teachers and book reviewers." },
  { title: "Customer proof", levers: ["get", "keep"], owner: "content",
    trigger: "Support or the community sees a happy customer or a great result.",
    steps: [["support", "Flags the story and asks permission"], ["legal", "Checks there is no misleading claim"], ["content", "Makes a testimonial clip or case study"], ["design", "Adds it to the landing page"], ["ads", "Uses it as creative"], ["sales", "Adds it to the partner kit"]],
    metric: "Landing page conversion rate", example: "Children's books: a parent's video of their child reading the book." },
  { title: "Free tool as a lead magnet", levers: ["get"], owner: "engineering",
    trigger: "SEO finds a tool people search for.",
    steps: [["seo", "Confirms search volume for the tool"], ["engineering", "Builds the free tool"], ["design", "Designs it to match the brand"], ["content", "Makes a demo video"], ["email", "Offers \"email me the result\""], ["data", "Tracks tool use to sign-up"]],
    metric: "Tool users who sign up", example: "Sports data: an odds converter. Children's books: free printable activity sheets." },
  { title: "Launch week", levers: ["get", "keep"], owner: "engineering",
    trigger: "A feature, market or product is ready to ship.",
    steps: [["engineering", "Ships behind tracking"], ["legal", "Checks launch claims"], ["design", "Makes launch assets"], ["content", "Launch video and posts"], ["email", "Announces to the list, by segment"], ["sales", "Partners announce too"], ["support", "Has the FAQ ready before launch"], ["ads", "Runs the launch campaign"], ["data", "Reports adoption and sign-ups in week one"]],
    metric: "Sign-ups and feature adoption in week one", example: "Sports data: a new board launches. Children's books: a new title is released." },
  { title: "Paid ads with a payback cap", levers: ["get"], owner: "ads",
    trigger: "A creative has proven itself organically.",
    steps: [["content", "Supplies the proven organic creative"], ["legal", "Checks platform rules (regulated industries, age gates, children's content)"], ["design", "Builds landing variants"], ["ads", "Tests creatives and audiences"], ["data", "Reports cost to win by creative and channel"], ["finance", "Caps spend where payback goes over 12 months"], ["ceo", "Approves the budget"]],
    metric: "Cost to win a customer; payback months", example: "Children's books: boost the best story-time reel to parents." },
  { title: "Community invites", levers: ["get"], owner: "support",
    trigger: "Members are active in the free community.",
    steps: [["support", "Runs the free section"], ["content", "Posts daily free tips or recaps"], ["engineering", "Builds invite links with rewards"], ["legal", "Adds any required safety messaging"], ["data", "Tracks invited members who become paying"]],
    metric: "Invited members who convert", example: "Sports data: a free tips channel in the community." },
  { title: "Original data for press and AI answers", levers: ["get"], owner: "seo",
    trigger: "Monthly: there is data nobody else has.",
    steps: [["data", "Pulls an original statistic"], ["content", "Turns it into a report and charts"], ["legal", "Checks the data claims"], ["seo", "Adds structured data so AI answers cite it"], ["sales", "Pitches journalists and podcasts"]],
    metric: "Citations, backlinks and referral sign-ups", example: "Sports data: bookmaker margin by sport, every month." },
  { title: "Daily blog from search demand", levers: ["get"], owner: "seo",
    trigger: "Every day: a search the site shows for but ranks poorly on, or a gap in what rivals publish.",
    steps: [["data", "Finds searches the site shows for but ranks poorly on"], ["competitors", "Notes what rivals cover that the business doesn't"], ["seo", "Picks one topic with real demand"], ["content", "Writes a sourced post in the brand voice"], ["legal", "Checks claims against the regulated rules"], ["engineering", "Publishes it and reads it back"], ["data", "Measures clicks and sign-ups from posts"]],
    metric: "Search clicks and sign-ups from posts", example: "Coffee subscription: \"how long does cold brew keep\" sits on page 3, so today's post answers it." },
  { title: "Trial that didn't convert", metricId: "new_paying", levers: ["get"], owner: "email",
    trigger: "A trial ends without the customer reaching first value.",
    steps: [["data", "Flags trials that never activated"], ["email", "Sends a help sequence aimed at the missing step"], ["sales", "Reaches out personally to high-intent leads"], ["engineering", "Fixes the step most people drop at"], ["support", "Offers a short walkthrough"]],
    metric: "Trial-to-paid rate", example: "Sports data: signed up but never tracked a bet." },
  { title: "Abandoned checkout recovery", metricId: "new_paying", levers: ["get"], owner: "email",
    trigger: "Someone starts a checkout and hasn't paid a few hours later.",
    steps: [["data", "Lists unfinished checkouts, leaving out the owner's and test accounts"], ["legal", "Confirms the consent basis for a follow-up"], ["email", "Sends one note asking what stopped them, with a link to finish"], ["support", "Answers the replies personally"], ["finance", "Fixes payment errors the replies reveal"], ["data", "Counts checkouts recovered after the email"]],
    metric: "Checkouts recovered; new paying customers", example: "Software subscription: someone stopped at the payment step or couldn't find the plan they needed." },
  { title: "Pricing page experiment", levers: ["get", "expand"], owner: "finance",
    trigger: "Visitor-to-paid conversion is flat or falling.",
    steps: [["data", "Sets the baseline"], ["competitors", "Collects rivals' pricing pages"], ["finance", "Proposes options (free tier or trial, annual discount)"], ["design", "Builds the variants"], ["legal", "Checks price display rules"], ["engineering", "Ships the test"], ["data", "Measures"], ["ceo", "Decides"]],
    metric: "Visitor-to-paid rate", example: "Two-tier subscription: how the tiers are shown on the pricing page." },
  { title: "New market or category", levers: ["get", "keep"], owner: "engineering",
    trigger: "Searches, requests or a rival show demand for something you don't cover.",
    steps: [["competitors", "Shows who covers it already"], ["data", "Counts searches and requests"], ["legal", "Checks licensing for the region"], ["engineering", "Adds the market or category"], ["seo", "Builds its pages"], ["content", "Makes launch content"], ["ads", "Runs a local campaign"], ["support", "Updates FAQs"]],
    metric: "Sign-ups from the new market", example: "Sports data: a new league's season starts." },
  { title: "Podcast and creator appearances", levers: ["get"], owner: "sales",
    trigger: "A booking is confirmed.",
    steps: [["sales", "Books the appearance"], ["content", "Prepares talking points"], ["finance", "Sets a show-specific promo code"], ["content", "Repurposes the appearance into clips"], ["seo", "Gets the backlink"], ["data", "Tracks code redemptions"]],
    metric: "Promo code redemptions", example: "Founder: guest spots on business podcasts." },
  { title: "Referral program", levers: ["get", "expand"], owner: "engineering",
    trigger: "Customers are activated and happy.",
    steps: [["finance", "Sets the reward (credit or a free month)"], ["legal", "Writes the terms"], ["engineering", "Builds referral links and rewards"], ["design", "Designs the share screen"], ["email", "Announces it to active customers"], ["data", "Attributes referrals and checks for fraud"]],
    metric: "Customers from referrals", example: "Subscription: a free month for each friend who subscribes." },
  // ---------------- Keep customers
  { title: "Onboarding to first value", metricId: "activation_rate", levers: ["keep"], owner: "engineering",
    trigger: "A new customer signs up.",
    steps: [["data", "Defines the activation moment"], ["design", "Makes a first screen with one goal"], ["email", "Sends day 0, 1, 3 and 7 onboarding emails"], ["content", "Makes 60-second \"first week\" videos"], ["support", "Messages anyone stuck at day 3"], ["data", "Reports time to activation by cohort"]],
    metric: "Share of new customers activated within 7 days", example: "Sports data: first bet tracked or first alert set. Children's books: first story read." },
  { title: "Churn early warning", metricId: "paying_churn_rate", levers: ["keep"], owner: "email",
    trigger: "A customer's risk score crosses the threshold.",
    steps: [["data", "Scores risk daily (no login for 7 days, less activity, a failed payment, a complaint)"], ["email", "Sends a nudge showing what's new for them"], ["support", "Writes personally to high-value customers"], ["engineering", "Checks whether a bug or missing data caused it"], ["ceo", "Reviews the risk list weekly"]],
    metric: "Churn of flagged customers who were helped vs not", example: "A top-tier member stops opening alerts after a bad week." },
  { title: "Voice of the customer to roadmap", levers: ["keep", "expand"], owner: "engineering",
    trigger: "Weekly: tickets and community messages are tagged.",
    steps: [["support", "Tags every ticket and complaint"], ["data", "Ranks themes by revenue at risk"], ["competitors", "Checks whether a rival already solves it"], ["engineering", "Decides and writes the decision to the vault"], ["engineering", "Builds it"], ["content", "Makes \"you asked, we built\" content"], ["email", "Tells the people who asked"], ["support", "Replies to every original request"]],
    metric: "Churn among customers who asked; requests closed", example: "Sports data: repeated requests for a missing bookmaker." },
  { title: "Competitor move to product response", levers: ["keep", "expand"], owner: "engineering",
    trigger: "Market & Competitors detects a rival launch, price cut or new market.",
    steps: [["competitors", "Writes a brief with links"], ["support", "Reports what customers say about the rival"], ["data", "Checks whether churners mention the rival"], ["engineering", "Decides: match, beat or ignore"], ["finance", "Models the impact if it's a price move"], ["engineering", "Builds the response"], ["content", "Makes the comparison or announcement"], ["email", "Tells the at-risk segment first"], ["sales", "Gives partners the answer"]],
    metric: "Customers lost to that rival; win rate against it", example: "A rival adds a feature; ours ships with better data and is shown to at-risk members first." },
  { title: "Data freshness and uptime", levers: ["keep"], owner: "security",
    trigger: "A monitor fires: a site is down or a data feed is stale.",
    steps: [["security", "Detects it (uptime monitor, data health checks)"], ["support", "Is told before customers notice"], ["engineering", "Finds and fixes the root cause"], ["email", "Sends a status note if customers saw it"], ["finance", "Credits customers if a paid feature was down a long time"], ["data", "Logs minutes stale and tickets per incident"]],
    metric: "Incidents, minutes of stale data, tickets per incident", example: "A data feed stalls and customers see stale numbers, which they read as a broken product." },
  { title: "Failed payment recovery", metricId: "payment_recovery_rate", levers: ["keep"], owner: "finance",
    trigger: "A card or store payment fails.",
    steps: [["finance", "Detects the failed payment"], ["email", "Sends reminders on day 0, 3 and 7"], ["engineering", "Shows an in-app banner to update the card"], ["support", "Contacts high-value customers personally"], ["data", "Reports the recovery rate"]],
    metric: "Share of failed payments recovered", example: "Often a large share of churn is a failed card, not a decision to leave." },
  { title: "Cancel flow with saves", metricId: "paying_churn_rate", levers: ["keep"], owner: "engineering",
    trigger: "A customer starts to cancel.",
    steps: [["engineering", "Asks for the reason in one tap"], ["finance", "Offers a save within margin (pause, downgrade, discount)"], ["legal", "Keeps cancelling easy and lawful"], ["data", "Ranks the reasons"], ["support", "Follows up on \"missing feature\" reasons"], ["email", "Queues a win-back"]],
    metric: "Save rate; top cancel reasons", example: "Seasonal product: offer a pause instead of a cancel." },
  { title: "Win-back when the reason is fixed", levers: ["keep"], owner: "email",
    trigger: "A fix ships for a common cancel reason.",
    steps: [["data", "Lists churned customers by reason"], ["engineering", "Ships the fix"], ["finance", "Approves a comeback offer"], ["legal", "Checks consent to email them"], ["email", "Sends \"you left because of X; X is fixed\""], ["ads", "Retargets churned customers"]],
    metric: "Reactivated customers", example: "Former customers who left over a missing feature." },
  { title: "Daily habit", metricId: "weekly_active_rate", levers: ["keep"], owner: "content",
    trigger: "Every day.",
    steps: [["engineering", "Sends alerts for the customer's interests"], ["content", "Posts a daily recap or tip"], ["support", "Runs daily community threads"], ["email", "Sends a weekly digest"], ["data", "Reports the weekly active share"]],
    metric: "Weekly active customers", example: "Sports data: daily free tips and a results recap. Children's books: a story of the week." },
  { title: "Honest track record", levers: ["keep", "get"], owner: "data",
    trigger: "Picks or results settle.",
    steps: [["data", "Grades every result, losses included"], ["legal", "Checks the record isn't misleading"], ["content", "Posts the weekly recap"], ["engineering", "Shows the record in the product"], ["support", "Handles disputes about results"]],
    metric: "Churn after bad weeks", example: "Sports data: a weekly results recap, losses included." },
  { title: "Customer academy", levers: ["keep", "get"], owner: "content",
    trigger: "Support's top 20 questions.",
    steps: [["support", "Lists the top questions"], ["content", "Makes short lessons"], ["seo", "Lets the lessons rank"], ["email", "Drips them to new customers"], ["engineering", "Links them from the right screens"]],
    metric: "Activation and retention of academy viewers", example: "Sports data: value and bankroll basics." },
  { title: "Off-season plan", levers: ["keep"], owner: "engineering",
    trigger: "A season or peak period is about to end.",
    steps: [["data", "Finds customers who only use the seasonal part"], ["competitors", "Checks what rivals do off-season"], ["engineering", "Highlights what's still live"], ["finance", "Offers a pause instead of cancelling"], ["content", "Makes off-season content"], ["email", "Schedules pre-season reactivation"]],
    metric: "Churn in off-season months", example: "Sports data: one sport's off-season." },
  { title: "Release quality gate", levers: ["keep"], owner: "engineering",
    trigger: "Before every release.",
    steps: [["engineering", "Runs tests and screen checks"], ["security", "Has the rollback ready"], ["support", "Gets the release notes"], ["data", "Watches error rates after release"]],
    metric: "Bugs that reach customers", example: "HQ: screen checks caught a stale review before anyone acted on it." },
  { title: "Top customer care", levers: ["keep", "expand"], owner: "support",
    trigger: "Monthly.",
    steps: [["data", "Lists the top 10% by revenue"], ["support", "Gives them a named contact and check-ins"], ["sales", "Writes an account plan"], ["engineering", "Offers early access"], ["email", "Sends VIP-only updates"]],
    metric: "Retention and expansion of top customers", example: "Top-tier members and partners." },
  { title: "Exit survey to competitive intel", levers: ["keep"], owner: "data",
    trigger: "A cancel reason names a rival.",
    steps: [["engineering", "Collects the reason at cancel"], ["data", "Tags \"went to rival X\""], ["competitors", "Adds X to the watch list"], ["engineering", "Feeds the competitor-response workflow"]],
    metric: "Share of churn going to each rival", example: "Which rival keeps winning your customers." },
  { title: "Account security and trust", levers: ["keep", "base"], owner: "security",
    trigger: "A suspicious login, breach report or new risk.",
    steps: [["security", "Runs 2FA, breach monitoring and backups"], ["support", "Uses a scripted response"], ["legal", "Handles notification duties"], ["content", "Keeps a trust and security page"]],
    metric: "Account incidents", example: "Accounts that hold history and linked services." },
  // ---------------- Expand revenue
  { title: "Usage limit to upgrade", levers: ["expand"], owner: "engineering",
    trigger: "A customer hits a limit or a gated feature.",
    steps: [["data", "Finds who hits limits often"], ["engineering", "Shows an upgrade prompt in context, with what they'd get"], ["design", "Designs the upgrade screen"], ["finance", "Sets the price and annual option"], ["email", "Follows up with their own usage numbers"], ["support", "Answers questions"]],
    metric: "Upgrade rate from the prompt", example: "Mid-tier members opening top-tier features." },
  { title: "Tier design", levers: ["expand", "keep"], owner: "finance",
    trigger: "Quarterly, or after a big launch.",
    steps: [["data", "Shows which features are used and which retain customers"], ["competitors", "Compares rivals' tiers"], ["engineering", "Sets the gates"], ["finance", "Sets price points"], ["legal", "Checks price display"], ["content", "Explains the tiers"], ["support", "Updates the FAQ"]],
    metric: "Revenue per customer; net revenue retention", example: "What belongs in each tier." },
  { title: "Monthly to annual", levers: ["expand"], owner: "finance",
    trigger: "A customer is active in month two or three.",
    steps: [["data", "Finds active monthly customers"], ["finance", "Sets the annual discount"], ["engineering", "Shows the offer in the product"], ["email", "Sends the offer"]],
    metric: "Share of customers on annual; cash collected", example: "Any subscription." },
  { title: "Add-ons", levers: ["expand"], owner: "engineering",
    trigger: "Repeated requests for something beyond the core plan.",
    steps: [["support", "Collects the requests"], ["sales", "Confirms willingness to pay"], ["engineering", "Builds the add-on"], ["finance", "Prices it"], ["legal", "Checks the terms"], ["content", "Makes a demo"], ["email", "Offers it to the right segment"]],
    metric: "Add-on attach rate", example: "Sports data: automated tracking or a browser extension as paid extras." },
  { title: "Teams and B2B", levers: ["expand"], owner: "sales",
    trigger: "Accounts share logins, or someone asks for seats or an API.",
    steps: [["data", "Spots shared logins and heavy use"], ["support", "Passes on requests for seats or an API"], ["sales", "Offers a team plan or API access"], ["legal", "Writes the contract"], ["engineering", "Builds seats and admin"], ["finance", "Handles invoicing"]],
    metric: "B2B revenue", example: "Sports data: syndicates and tipster groups; data via an API." },
  { title: "Support conversation to upgrade", levers: ["expand"], owner: "support",
    trigger: "A customer asks for something the next tier already does.",
    steps: [["support", "Answers and tags the need"], ["email", "Sends a tailored upgrade offer"], ["sales", "Handles larger accounts"], ["data", "Tracks conversion from tagged chats"]],
    metric: "Upgrades from support", example: "\"Can I get alerts for this?\" when alerts are a top-tier feature." },
  { title: "Price increase without churn", levers: ["expand"], owner: "finance",
    trigger: "Costs rise or the product has clearly grown.",
    steps: [["data", "Estimates sensitivity by cohort"], ["finance", "Sets the new price and who keeps the old one"], ["legal", "Checks notice periods"], ["content", "Explains the added value first"], ["email", "Announces it with notice"], ["support", "Gets scripts ready"], ["data", "Watches churn for 60 days"]],
    metric: "Revenue gain vs extra churn", example: "Any subscription after a year of new features." },
  { title: "Cross-sell across your businesses", levers: ["expand"], owner: "sales",
    trigger: "Two businesses serve overlapping customers.",
    steps: [["data", "Measures the overlap"], ["legal", "Checks consent to market across businesses"], ["sales", "Designs the offer"], ["email", "Sends it to the overlap"], ["finance", "Tracks revenue per business"]],
    metric: "Cross-sell revenue", example: "Subscribers to a data API; book buyers to the next series." },
  { title: "Premium content products", levers: ["expand"], owner: "content",
    trigger: "A topic gets far more attention than others.",
    steps: [["data", "Finds the topics customers return to"], ["content", "Makes a course or guide"], ["finance", "Prices it"], ["legal", "Checks claims"], ["email", "Launches it to existing customers"]],
    metric: "Sales to existing customers", example: "Children's books: a reading-routine guide for parents." },
  // ---------------- Foundation
  { title: "Weekly growth review", metricId: "mrr", levers: ["base", "get", "keep", "expand"], owner: "ceo",
    trigger: "Every week.",
    steps: [["data", "Publishes the scorecard"], ["ceo", "Picks the weakest lever"], ["ceo", "Names one owner and contributors for each action"], ["operations", "Tracks the actions in the vault"], ["data", "Measures the result next week"]],
    metric: "The weakest lever's number, week on week", example: "HQ: the CEO tab and /hq:ceo." },
  { title: "Unit economics check", levers: ["base"], owner: "finance",
    trigger: "Monthly.",
    steps: [["data", "Reports cost to win by channel and lifetime value by tier"], ["finance", "Sets the payback limit"], ["ads", "Adjusts budgets"], ["sales", "Adjusts commissions"], ["finance", "Sets discount limits"]],
    metric: "Lifetime value vs cost to win; payback months", example: "Rule of thumb: value at least 3x cost, payback within 12 months." },
  { title: "Measurement plumbing", levers: ["base"], owner: "data",
    trigger: "Any new feature, channel or campaign.",
    steps: [["data", "Writes the tracking plan"], ["engineering", "Adds the events"], ["legal", "Checks privacy and consent"], ["data", "Sets campaign tags and attribution"], ["security", "Keeps the data safe and backed up"]],
    metric: "Share of customers with a known source", example: "Any business: web analytics plus campaign tags." },
  { title: "Claims and compliance review", levers: ["base"], owner: "legal",
    trigger: "Anything customer-facing before it ships.",
    steps: [["content", "Submits posts, ads and emails with claims"], ["legal", "Checks regulated-industry rules, children's privacy, spam consent and platform policies"], ["operations", "Logs decisions as reusable rules"]],
    metric: "Rejected ads and complaints", example: "Regulated products: no guaranteed-outcome language. Children's products: children's privacy." },
  { title: "Brand system", levers: ["base"], owner: "design",
    trigger: "Any new channel, product or template.",
    steps: [["design", "Keeps the brand kit current"], ["content", "Uses it in every post"], ["engineering", "Uses it on every screen"], ["ads", "Uses it in every creative"]],
    metric: "Consistency across channels", example: "Any business." },
  { title: "Capacity and hiring", levers: ["base"], owner: "people",
    trigger: "A lever's backlog grows faster than the work gets done.",
    steps: [["operations", "Shows the backlog by lever"], ["people", "Decides on a contractor or hire"], ["finance", "Approves the cost"], ["operations", "Onboards them with SOPs"]],
    metric: "Backlog age", example: "A video editor for a founder series." },
  { title: "Experiment log", levers: ["base"], owner: "data",
    trigger: "Every test.",
    steps: [["data", "Records the hypothesis before the test"], ["data", "Records the result after"], ["operations", "Files it in the vault"], ["ceo", "Reads it in the weekly review"]],
    metric: "Tests run; repeats avoided", example: "Hook tests across a video series." },
  { title: "Knowledge base and decisions", levers: ["base"], owner: "operations",
    trigger: "Any decision or new SOP.",
    steps: [["operations", "Writes it to the business's vault"], ["ceo", "Links it from the review"], ["people", "Uses it to onboard new people"]],
    metric: "Questions answered by the vault", example: "HQ: one Obsidian vault per business." },
];

/** Hand-offs a department sends or receives. */
export const edgesFor = (n: Node) => EDGES.filter((x) => x.from === n || x.to === n);

/** Workflows a department owns or contributes a step to. */
export const workflowsFor = (n: Node) => WORKFLOWS.filter((w) => w.owner === n || w.steps.some(([d]) => d === n));

/** The departments with the most hand-offs, busiest first. */
export function busiest(limit = 4): { node: Node; count: number }[] {
  const n: Record<string, number> = {};
  for (const x of EDGES) { n[x.from] = (n[x.from] ?? 0) + 1; n[x.to] = (n[x.to] ?? 0) + 1; }
  return Object.entries(n).sort((a, b) => b[1] - a[1]).slice(0, limit).map(([node, count]) => ({ node, count }));
}

/** The URL slug of a workflow: its title in kebab case ("Daily habit" → "daily-habit"). */
export const workflowSlug = (title: string) =>
  title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");

/** The workflow a slug names, or null. */
export const workflowBySlug = (slug: string): Workflow | null => WORKFLOWS.find((w) => workflowSlug(w.title) === slug) ?? null;
